### PR TITLE
Checks all custom actions for cycles. Version 3. 

### PR DESCRIPTION
**Pull request by cpuwzd**
Fixes wixtoolset/issues#6201

### CODE REVIEW

**Comment by cpuwzd** [comment]
@robmen,
This is the branch that is waiting to be merged.
Ron Martin

**Comment by robmen** [comment]
Yes, thanks. On my TODO list. Initial pass looks good, need to walk through the new algorithm.

**Comment by rseanhall** [comment]
@cpuwzd Please leave a comment on https://github.com/wixtoolset/issues/issues/6201 so I can assign it to you. It could be as simple as "Please assign this issue to me". Thanks.

**Review by robmen — APPROVED** [review]

**Comment by robmen** [comment]
This will be a nice check to have fully working. Will undoubtedly save someone(s) a lot of time in the future.

**Pull request merged**
