### PR TITLE
Improve Component Id and GUId handling and add RepairConditions

### PR DESCRIPTION
**Pull request by robmen**

### CODE REVIEW

**Comment by rseanhall** [comment]
As discussed [here](https://github.com/wixtoolset/Core/pull/252#discussion_r599850993), `ExePackage`s are not repairable without `RepairArguments`. `RepairCondition` should not be allowed there without them.

**Comment by robmen** [comment]
Yep. That check is wrapped up with the DetectCondition/Permanent check I've not settled on the final error/warnings.

**Comment by rseanhall** [comment]
Can you disable the compilation of `RepairCondition` for now? You're going to have to make a commit here anyway to get an updated Core so you can build an updated Tools so you can build Bal.wixext.

**Comment by robmen** [comment]
Yeah. Next.

**Pull request merged**
