### PR TITLE
Update decompiler to use XDocument rather than generated classes.

### PR DESCRIPTION
**Pull request by barnson**
- Use CompareXml for diffing.
- Change CustomAction/@ScriptFile to @ScriptSourceFile.

### CODE REVIEW

**Comment by rseanhall** [comment]
I don't understand how this is better or easier than the generated wix.cs. Are you going to be fixing Heat as well?

**Comment by barnson** [comment]
Well, I got rid of ~2000 lines of code, so I'd say it's better/easier. The generated code isn't designed to be human-editable so it would require coordination between even more repos than normal. I hadn't considered Heat, which is definitely something to consider.

**Comment by rseanhall** [comment]
It should be relatively easy to get the Data repo to consume the .xsd from whatever repo it lives in, and autogenerate wix.cs from there. Nothing in Data actually uses it, so it shouldn't matter if Intellisense works for it.

**Comment by barnson** [comment]
xsdgen doesn't provide enough value to make the machinations worth it (IMHO). Heat doesn't use much of it so it'd be straightforward to update Heat to use XElement or to import wix.cs like it did for the other namespaces.

**Pull request merged**
